### ISSUE TITLE
使用twp=>cn模式下出現錯誤

### ISSUE THREAD

**Issue by fei0316** [hddhyq/vscode-opencclint#2]
首先感謝閣下開發此插件！

如圖：
原文
![圖片](https://user-images.githubusercontent.com/8295915/207290906-ed103384-6947-4b13-ba47-5a6906dbfdf8.png)
結果
![圖片](https://user-images.githubusercontent.com/8295915/207290967-bb4e3952-c8e0-4166-8bcf-2443e4e93839.png)

看來好像與使用twp有關，當遇到文字長度不一（「解除安裝」>「卸载」）時會使用附近的文字填充。

謝謝！有需要時我也可以提供更多資料

**Comment by fei0316** [comment]
但也有些是無關，例如：
![圖片](https://user-images.githubusercontent.com/8295915/207291813-af07d812-1f50-42b8-aa2b-c093923f0028.png)
![圖片](https://user-images.githubusercontent.com/8295915/207291857-84d21756-b9ae-4773-b557-cee2751f28d8.png)

**Comment by hddhyq** [comment]
確實有這個問題，今天稍晚我會看一下，解決了同步給你。

**Comment by hddhyq** [comment]
@fei0316 v0.0.3修復了哈，安裝下最新的就好。
