### ISSUE TITLE
The keybinding for translateSelection (cmd+shift+p) overwrites the Command Palette keybinding in Mac

### ISSUE THREAD

**Issue by openopentw** [hddhyq/vscode-opencclint#5]
Hi,

Thanks for the extension. This is useful!

However, the keybinding for translateSelection (shift+cmd+p) overwrites the Command Palette keybinding in Mac. You can check it here: https://github.com/hddhyq/vscode-opencclint/blob/df41cfd70c64c741a68d3d51e8aee4b5a06a5b9d/package.json#L59

The keybinding for Command Palette is the most commonly used / referenced keybinding. It should not be overwritten and it may cause confusions!

It would be better to change it to some other keybindings like "ctrl+cmd+p" or "opt+cmd+p" etc.

I thought you may not be using a Mac so you did't notice it ;)

**Comment by hddhyq** [comment]
ok, i will fix it.

**Comment by hddhyq** [comment]
you can use the right-click menu first
